# Generated by Django 2.1.5 on 2019-05-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webVotingApp', '0002_auto_20190331_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='info_href',
            field=models.CharField(default='https://en.wikipedia.org/wiki/<django.db.models.fields.CharField>_<django.db.models.fields.CharField>', max_length=300),
        ),
    ]
