# Generated by Django 2.1.5 on 2019-03-31 19:49
from __future__ import unicode_literals

from django.core.exceptions import ObjectDoesNotExist
from django.db import migrations

AUTHORS =[
    {'first_name': 'Helen',
     'info_href': 'https://en.wikipedia.org/wiki/Helen_DeWitt',
     'last_name': 'DeWitt'},
    {'first_name': 'Jonathan',
     'info_href': 'https://en.wikipedia.org/wiki/Jonathan_Franzen',
     'last_name': 'Franzen'},
    {'first_name': 'Kazuo',
     'info_href': 'https://en.wikipedia.org/wiki/Kazuo_Ishiguro',
     'last_name': 'Ishiguro'},
    {'first_name': 'Sheila',
     'info_href': 'https://en.wikipedia.org/wiki/Sheila_Heti',
     'last_name': 'Heti'},
    {'first_name': 'Elena',
     'info_href': 'https://en.wikipedia.org/wiki/Elena_Ferrante',
     'last_name': 'Ferrante'},
    {'first_name': 'Maggie',
     'info_href': 'https://en.wikipedia.org/wiki/Maggie_Nelson',
     'last_name': 'Nelson'},
    {'first_name': 'Roberto',
     'info_href': 'https://en.wikipedia.org/wiki/Roberto_Bolano',
     'last_name': 'Bolano'},
    {'first_name': 'Paul',
     'info_href': 'https://en.wikipedia.org/wiki/Paul_Beatty',
     'last_name': 'Beatty'},
    {'first_name': 'Rachel',
     'info_href': 'https://en.wikipedia.org/wiki/Rachel_Cusk',
     'last_name': 'Cusk'},
    {'first_name': 'Ian',
     'info_href': 'https://en.wikipedia.org/wiki/Ian_McEwan',
     'last_name': 'McEwan'},
    {'first_name': 'Joan',
     'info_href': 'https://en.wikipedia.org/wiki/Joan_Didion',
     'last_name': 'Didion'},
    {'first_name': 'Ben',
     'info_href': 'https://en.wikipedia.org/wiki/Ben_Lerner',
     'last_name': 'Lerner'},
    {'first_name': 'Rachel',
     'info_href': 'https://en.wikipedia.org/wiki/Rachel_Kushner',
     'last_name': 'Kushner'},
    {'first_name': 'Percival',
     'info_href': 'https://en.wikipedia.org/wiki/Percival_Everett',
     'last_name': 'Everett'},
    {'first_name': 'Jeffrey',
     'info_href': 'https://en.wikipedia.org/wiki/Jeffrey_Eugenides',
     'last_name': 'Eugenides'},
    {'first_name': 'Michel',
     'info_href': 'https://en.wikipedia.org/wiki/Michel_Houellebecq',
     'last_name': 'Houellebecq'},
    {'first_name': 'Gary',
     'info_href': 'https://en.wikipedia.org/wiki/Gary_Indiana',
     'last_name': 'Indiana'},
    {'first_name': 'Edward',
     'info_href': 'https://en.wikipedia.org/wiki/Edward_Jones',
     'last_name': 'Jones'},
    {'first_name': 'Philip',
     'info_href': 'https://en.wikipedia.org/wiki/Philip_Roth',
     'last_name': 'Roth'},
    {'first_name': 'Alan',
     'info_href': 'https://en.wikipedia.org/wiki/Alan_Hollinghurst',
     'last_name': 'Hollinghurst'},
    {'first_name': 'Mary',
     'info_href': 'https://en.wikipedia.org/wiki/Mary_Gaitskill',
     'last_name': 'Gaitskill'},
    {'first_name': 'Cormac',
     'info_href': 'https://en.wikipedia.org/wiki/Cormac_McCarthy',
     'last_name': 'McCarthy'},
    {'first_name': 'Frederick',
     'info_href': 'https://en.wikipedia.org/wiki/Frederick_Seidel',
     'last_name': 'Seidel'},
    {'first_name': 'Junot',
     'info_href': 'https://en.wikipedia.org/wiki/Junot_Diaz',
     'last_name': 'Diaz'},
    {'first_name': 'Hilary',
     'info_href': 'https://en.wikipedia.org/wiki/Hilary_Mantel',
     'last_name': 'Mantel'},
    {'first_name': 'Elif',
     'info_href': 'https://en.wikipedia.org/wiki/Elif_Batuman',
     'last_name': 'Batuman'},
    {'first_name': 'Aimee',
     'info_href': 'https://en.wikipedia.org/wiki/Aimee_Bender',
     'last_name': 'Bender'},
    {'first_name': 'Helen',
     'info_href': 'https://en.wikipedia.org/wiki/Helen_Oyeyemi',
     'last_name': 'Oyeyemi'},
    {'first_name': 'Emmanuel',
     'info_href': 'https://en.wikipedia.org/wiki/Emmanuel_Carrere',
     'last_name': 'Carrere'},
    {'first_name': 'Colson',
     'info_href': 'https://en.wikipedia.org/wiki/Colson_Whitehead',
     'last_name': 'Whitehead'},
    {'first_name': 'Gillian',
     'info_href': 'https://en.wikipedia.org/wiki/Gillian_Flynn',
     'last_name': 'Flynn'},
    {'first_name': 'Zadie',
     'info_href': 'https://en.wikipedia.org/wiki/Zadie_Smith',
     'last_name': 'Smith'},
    {'first_name': 'Hilton',
     'info_href': 'https://en.wikipedia.org/wiki/Hilton_Als',
     'last_name': 'Als'},
    {'first_name': 'Karl Ove',
     'info_href': 'https://en.wikipedia.org/wiki/Karl Ove_Knausgaard',
     'last_name': 'Knausgaard'},
    {'first_name': 'Donna',
     'info_href': 'https://en.wikipedia.org/wiki/Donna_Tartt',
     'last_name': 'Tartt'},
    {'first_name': 'Jenny',
     'info_href': 'https://en.wikipedia.org/wiki/Jenny_Offill',
     'last_name': 'Offill'},
    {'first_name': 'Miriam',
     'info_href': 'https://en.wikipedia.org/wiki/Miriam_Toews',
     'last_name': 'Toews'},
    {'first_name': 'Claudia',
     'info_href': 'https://en.wikipedia.org/wiki/Claudia_Rankine',
     'last_name': 'Rankine'},
    {'first_name': 'Fred',
     'info_href': 'https://en.wikipedia.org/wiki/Fred_Moten',
     'last_name': 'Moten'}
     ]


def add_author_data(apps, schema_editor):
    author_class = apps.get_model('webVotingApp', 'Author')
    for author in AUTHORS:
        try:
            duplicate_object = author_class.objects.get(
                author_first_name=author['first_name'],
                author_last_name=author['last_name'],
                info_href=author['info_href']
            )
            print('Duplicate author entry not added to author table:',
                  author['first_name'], author['last_name']
                  )
        except ObjectDoesNotExist:
            author_object = author_class.objects.create(
                author_first_name=author['first_name'],
                author_last_name=author['last_name'],
                info_href=author['info_href']
            )


def remove_author_data(apps, schema_editor):
    author_class = apps.get_model('webVotingApp', 'Author')
    for author in AUTHORS:
        author_object = author_class.objects.get(
            author_first_name=author['first_name'],
            author_last_name=author['last_name']
        )
        author_object.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('webVotingApp', '0003_author_info_href'),
    ]

    operations = [migrations.RunPython(
        add_author_data,
        remove_author_data
    )
    ]
