# Generated by Django 2.1.5 on 2019-05-01 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webVotingApp', '0005_auto_20190501_2012'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('member_last_name', 'member_first_name')},
        ),
    ]
