# Generated by Django 2.1.5 on 2019-05-01 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webVotingApp', '0009_auto_20190501_2048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='judge',
            options={'ordering': ['year', 'member']},
        ),
    ]
