# Generated by Django 2.1.5 on 2019-05-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webVotingApp', '0010_auto_20190501_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='info_href',
            field=models.CharField(max_length=300),
        ),
    ]
