# Generated by Django 2.1.5 on 2019-05-04 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webVotingApp', '0011_auto_20190501_2101'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='judge',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='judge',
            name='member',
        ),
        migrations.RemoveField(
            model_name='judge',
            name='year',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='judge',
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='vote',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='judge',
        ),
        migrations.DeleteModel(
            name='Judge',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
