# Generated by Django 2.1.5 on 2019-05-04 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webVotingApp', '0012_auto_20190504_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('judge_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['year', 'member'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('criteria_1', models.CharField(choices=[('1', 'Poor'), ('2', 'Common'), ('3', 'Good'), ('4', 'Outstanding'), ('5', 'Superlative')], max_length=2)),
                ('criteria_2', models.CharField(choices=[('1', 'Poor'), ('2', 'Common'), ('3', 'Good'), ('4', 'Outstanding'), ('5', 'Superlative')], max_length=2)),
                ('criteria_3', models.CharField(choices=[('1', 'Poor'), ('2', 'Common'), ('3', 'Good'), ('4', 'Outstanding'), ('5', 'Superlative')], max_length=2)),
                ('criteria_4', models.CharField(choices=[('1', 'Poor'), ('2', 'Common'), ('3', 'Good'), ('4', 'Outstanding'), ('5', 'Superlative')], max_length=2)),
                ('criteria_5', models.CharField(choices=[('1', 'Poor'), ('2', 'Common'), ('3', 'Good'), ('4', 'Outstanding'), ('5', 'Superlative')], max_length=2)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='webVotingApp.Candidate')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='webVotingApp.Judge')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('vote_id', models.AutoField(primary_key=True, serialize=False)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote', to='webVotingApp.Candidate')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote', to='webVotingApp.Judge')),
            ],
        ),
        migrations.AddField(
            model_name='judge',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='judge', to='webVotingApp.Member'),
        ),
        migrations.AddField(
            model_name='judge',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge', to='webVotingApp.Year'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('judge', 'candidate')},
        ),
        migrations.AlterUniqueTogether(
            name='judge',
            unique_together={('year', 'member')},
        ),
    ]
