# Generated by Django 2.1.5 on 2019-05-04 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webVotingApp', '0013_auto_20190504_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='member',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='member',
            name='location',
        ),
    ]
