# Generated by Django 2.1.5 on 2019-05-05 15:50

from django.db import migrations

GROUPS = [
    {
        'name': 'wva_member',
    },
    {
        'name': 'wva_coordinator',
    },
    {
        'name': 'wva_selection_committee',
    },
    {
        'name': 'wva_judge'
    }
]


def add_group_data(apps, schema_editor):
    group_model_class = apps.get_model('auth', 'Group')
    for group in GROUPS:
        group_object = group_model_class.objects.create(
            name=group['name'],
        )


def remove_group_data(apps, schema_editor):
    group_model_class = apps.get_model('auth', 'Group')
    for group in GROUPS:
        group_object = group_model_class.objects.get(
            name=group['name']
        )
        group_object.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('webVotingApp', '0016_dummy_author_data'),
    ]

    operations = [
        migrations.RunPython(
            add_group_data,
            remove_group_data
        )
    ]
