# Generated by Django 2.1.5 on 2019-05-05 22:21

from django.db import migrations
GROUPS = [
    {'name': 'wva_sysadmin'}
]


def add_group_data(apps, schema_editor):
    group_model_class = apps.get_model('auth', 'Group')
    for group in GROUPS:
        group_object = group_model_class.objects.create(
            name=group['name'],
        )


def remove_group_data(apps, schema_editor):
    group_model_class = apps.get_model('auth', 'Group')
    for group in GROUPS:
        group_object = group_model_class.objects.get(
            name=group['name']
        )
        group_object.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('webVotingApp', '0019_add_judge_group'),
    ]

    operations = [
        migrations.RunPython(
            add_group_data,
            remove_group_data
        )
    ]
