# Generated by Django 2.1.5 on 2019-05-06 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webVotingApp', '0020_add_sys_admin_group'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('judge', 'candidate')},
        ),
    ]
